   WinActivate("Visa Test System")
   WinMenuSelectItem("Visa Test System", "", "&Edit", "&Message Editor...")
   sleep(4000)
   WinActivate("Message Editor")
   WinSetState("Message Editor", "", @SW_MAXIMIZE)
   ControlCommand("Message Editor", "", "[CLASS:Button; INSTANCE:4]", "Uncheck", "")